{
 "title": "Service Health Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(http_server_requests_seconds_count,$service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "JVM Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (service) (\r\n  jvm_memory_used_bytes{\r\n    area=\"heap\",\r\n    service=\"$service\"\r\n  }\r\n)\r\n",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "sum by (service) (\r\n  jvm_memory_max_bytes{\r\n    area=\"heap\",\r\n    service=\"$service\"\r\n  }\r\n)\r\n",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "CPU Usage per service",
   "type": "timeseries",
   "description": "JVM process CPU usage per service",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (service)(process_cpu_usage{service=\"$service\"})",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "sum by (service)(avg_over_time(process_cpu_usage{service=\"$service\"}[5m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Request Rate (req/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(http_server_requests_seconds_count{service=\"$service\"}[5m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum(\r\n  rate(http_server_requests_seconds_count{service=\"$service\", status=~\"5..\"}[5m])\r\n)\r\nor vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency P95 (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le)(\r\n    rate(http_server_requests_seconds_bucket{service=\"$service\"}[5m])\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service)(up{service=\"$service\"})",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}