service:
  type: ClusterIP
  port: 9090

server:
  global:
    scrape_interval: 15s

# Scrape Spring Boot actuator endpoints
extraScrapeConfigs: |
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8081']

  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-service:8082']
