apiVersion: v2
name: shopease-monitoring
description: Monitoring stack for Shopease
type: application
version: 0.1.0

dependencies:
  - name: kube-prometheus-stack
    version: "58.*"
    repository: https://prometheus-community.github.io/helm-charts
